/**
 * Recipe Finder - Comprehensive Recipe Dataset
 * Includes diverse cuisines, dietary categories, traditional & heritage dishes,
 * nutrition info, spicy levels, and detailed steps.
 */

const RECIPES_DATA = [
    {
        id: 1,
        name: "Royal Chicken Biryani",
        tagline: "Fragrant basmati rice layered with spiced marinated chicken, saffron & caramelized onions.",
        cuisine: "Indian",
        category: "Non-Vegetarian",
        diet: "Non-Vegetarian",
        time: 50,
        prepTime: 20,
        cookTime: 30,
        difficulty: "Medium",
        rating: 4.9,
        reviewsCount: 342,
        calories: 620,
        servings: 4,
        spicyLevel: 3,
        featured: true,
        popular: true,
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Sanjeev R.",
        ingredients: [
            { name: "Basmati Rice", amount: 2, unit: "cups" },
            { name: "Chicken Breast / Thighs (cut in pieces)", amount: 500, unit: "g" },
            { name: "Plain Greek Yogurt", amount: 0.5, unit: "cup" },
            { name: "Large Onions (thinly sliced & fried)", amount: 2, unit: "items" },
            { name: "Ginger Garlic Paste", amount: 2, unit: "tbsp" },
            { name: "Garam Masala & Biryani Spice Mix", amount: 1.5, unit: "tbsp" },
            { name: "Turmeric Powder", amount: 0.5, unit: "tsp" },
            { name: "Red Chili Powder", amount: 1, unit: "tsp" },
            { name: "Fresh Mint & Coriander Leaves", amount: 0.5, unit: "cup" },
            { name: "Saffron strands soaked in warm milk", amount: 3, unit: "tbsp" },
            { name: "Ghee or Butter", amount: 2, unit: "tbsp" },
            { name: "Salt", amount: 1.5, unit: "tsp" }
        ],
        instructions: [
            "Marinate the chicken pieces with yogurt, ginger garlic paste, red chili powder, turmeric, garam masala, half of the fried onions, and salt for at least 30 minutes.",
            "Rinse basmati rice thoroughly and soak in water for 20 minutes. Boil in a large pot with whole spices (cloves, cardamom, cinnamon) until 70% cooked. Drain and set aside.",
            "Heat ghee in a heavy-bottom pot or Dutch oven. Add the marinated chicken and sear over medium heat for 7-8 minutes until partially cooked.",
            "Layer the parboiled basmati rice evenly over the cooked chicken.",
            "Top with saffron milk, remaining crispy fried onions, fresh mint leaves, and a drizzle of ghee.",
            "Seal the pot with a tight lid or aluminum foil. Cook on low heat (Dum) for 20 minutes.",
            "Let rest for 5 minutes, gently fluff with a fork from bottom to top, and serve piping hot with raita."
        ],
        nutrition: {
            calories: "620 kcal",
            protein: "38g",
            carbs: "72g",
            fat: "18g",
            fiber: "4g"
        }
    },
    {
        id: 2,
        name: "Creamy Tuscan Garlic Pasta",
        tagline: "Silky fettuccine tossed in a rich sun-dried tomato, spinach, and garlic parmesan cream sauce.",
        cuisine: "Italian",
        category: "Vegetarian",
        diet: "Vegetarian",
        time: 25,
        prepTime: 10,
        cookTime: 15,
        difficulty: "Easy",
        rating: 4.8,
        reviewsCount: 289,
        calories: 540,
        servings: 2,
        spicyLevel: 1,
        featured: true,
        popular: true,
        image: "https://images.unsplash.com/photo-1621996346565-e3d5d6281699?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Isabella M.",
        ingredients: [
            { name: "Fettuccine or Penne Pasta", amount: 250, unit: "g" },
            { name: "Heavy Cream (or Coconut Cream for vegan)", amount: 1, unit: "cup" },
            { name: "Garlic (minced)", amount: 4, unit: "cloves" },
            { name: "Sun-Dried Tomatoes (drained & chopped)", amount: 0.5, unit: "cup" },
            { name: "Fresh Baby Spinach", amount: 2, unit: "cups" },
            { name: "Grated Parmesan Cheese", amount: 0.5, unit: "cup" },
            { name: "Extra Virgin Olive Oil", amount: 1.5, unit: "tbsp" },
            { name: "Italian Herb Seasoning & Oregano", amount: 1, unit: "tsp" },
            { name: "Salt and Black Pepper", amount: 1, unit: "pinch" }
        ],
        instructions: [
            "Bring a large pot of salted water to a boil. Cook pasta according to package directions until al dente. Reserve 1/2 cup pasta water, then drain.",
            "In a large skillet over medium heat, warm olive oil. Add minced garlic and sauté for 1 minute until fragrant (do not burn).",
            "Add sun-dried tomatoes and cook for 2 minutes to release their sweet flavor.",
            "Pour in the heavy cream and bring to a gentle simmer. Lower heat and stir in grated Parmesan cheese until melted and smooth.",
            "Add fresh baby spinach and Italian seasoning. Cook until spinach just wilts.",
            "Toss the drained pasta into the sauce, stirring to coat completely. Add a splash of pasta water if sauce gets too thick.",
            "Season with black pepper and salt to taste. Garnish with extra parmesan and fresh basil."
        ],
        nutrition: {
            calories: "540 kcal",
            protein: "16g",
            carbs: "62g",
            fat: "24g",
            fiber: "5g"
        }
    },
    {
        id: 3,
        name: "Artisan Margherita Pizza",
        tagline: "Classic Neapolitan crust topped with San Marzano tomato sauce, fresh mozzarella & sweet basil.",
        cuisine: "Italian",
        category: "Vegetarian",
        diet: "Vegetarian",
        time: 30,
        prepTime: 15,
        cookTime: 15,
        difficulty: "Medium",
        rating: 4.7,
        reviewsCount: 215,
        calories: 480,
        servings: 3,
        spicyLevel: 1,
        featured: false,
        popular: true,
        image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Marco V.",
        ingredients: [
            { name: "Pizza Dough Ball", amount: 1, unit: "item" },
            { name: "Crushed San Marzano Tomatoes", amount: 0.75, unit: "cup" },
            { name: "Fresh Mozzarella Cheese (sliced/torn)", amount: 150, unit: "g" },
            { name: "Fresh Basil Leaves", amount: 8, unit: "leaves" },
            { name: "Extra Virgin Olive Oil", amount: 1, unit: "tbsp" },
            { name: "Sea Salt & Oregano", amount: 1, unit: "pinch" }
        ],
        instructions: [
            "Preheat oven with a pizza stone or baking tray at maximum temperature (250°C / 480°F) for 20 minutes.",
            "Stretch the pizza dough on a floured surface into a 12-inch round with a slightly thicker crust edge.",
            "Spread the crushed tomato sauce evenly over the dough, leaving a 1/2 inch border.",
            "Distribute fresh mozzarella slices evenly across the sauce.",
            "Bake for 10-12 minutes until the crust is golden-brown and the cheese is bubbly with blistered spots.",
            "Remove from oven, immediately top with fresh basil leaves, drizzle with extra virgin olive oil, and slice."
        ],
        nutrition: {
            calories: "480 kcal",
            protein: "19g",
            carbs: "58g",
            fat: "18g",
            fiber: "3g"
        }
    },
    {
        id: 4,
        name: "Crispy Masala Dosa with Sambar",
        tagline: "Golden fermented crepe stuffed with spiced potato mash, served with coconut chutney.",
        cuisine: "Indian",
        category: "Vegetarian",
        diet: "Vegetarian",
        time: 35,
        prepTime: 15,
        cookTime: 20,
        difficulty: "Medium",
        rating: 4.8,
        reviewsCount: 310,
        calories: 360,
        servings: 2,
        spicyLevel: 2,
        featured: true,
        popular: true,
        image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Lakshmi N.",
        ingredients: [
            { name: "Fermented Dosa Batter", amount: 2, unit: "cups" },
            { name: "Boiled Potatoes (mashed coarsely)", amount: 3, unit: "medium" },
            { name: "Onion (thinly sliced)", amount: 1, unit: "item" },
            { name: "Green Chilies (chopped)", amount: 2, unit: "items" },
            { name: "Mustard Seeds & Curry Leaves", amount: 1, unit: "tsp" },
            { name: "Turmeric Powder", amount: 0.5, unit: "tsp" },
            { name: "Butter or Sesame Oil for roasting", amount: 2, unit: "tbsp" },
            { name: "Salt", amount: 1, unit: "tsp" }
        ],
        instructions: [
            "For potato masala: Heat 1 tbsp oil in a pan. Splutter mustard seeds, then add curry leaves, green chilies, and sliced onions. Sauté until translucent.",
            "Add turmeric powder, salt, and mashed boiled potatoes. Mix well with 3 tbsp of water. Cook for 3 minutes, then remove from heat.",
            "Heat a non-stick or cast-iron tawa (griddle). Lightly wipe with oil and sprinkle water drops to cool slightly.",
            "Pour a ladle of dosa batter into the center and quickly spread in a spiral outwards to form a thin circle.",
            "Drizzle butter or oil around edges. Cook on medium-high until the base turns deep golden and crisp.",
            "Place a portion of potato masala in the center. Fold the dosa into a cylinder or triangle.",
            "Serve immediately with fresh coconut chutney and hot lentil sambar."
        ],
        nutrition: {
            calories: "360 kcal",
            protein: "9g",
            carbs: "54g",
            fat: "12g",
            fiber: "4g"
        }
    },
    {
        id: 5,
        name: "Szechuan Kung Pao Chicken",
        tagline: "Fiery stir-fried chicken with crunchy peanuts, bell peppers, scallions, and dried red chilies.",
        cuisine: "Chinese",
        category: "Non-Vegetarian",
        diet: "Non-Vegetarian",
        time: 20,
        prepTime: 10,
        cookTime: 10,
        difficulty: "Easy",
        rating: 4.8,
        reviewsCount: 195,
        calories: 450,
        servings: 2,
        spicyLevel: 4,
        featured: false,
        popular: true,
        image: "https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Wei Chen",
        ingredients: [
            { name: "Chicken Breast (diced into cubes)", amount: 400, unit: "g" },
            { name: "Roasted Peanuts", amount: 0.3, unit: "cup" },
            { name: "Dried Red Szechuan Chilies", amount: 6, unit: "items" },
            { name: "Bell Pepper (cubed)", amount: 1, unit: "item" },
            { name: "Soy Sauce (Light & Dark)", amount: 2, unit: "tbsp" },
            { name: "Rice Vinegar & Sesame Oil", amount: 1, unit: "tbsp" },
            { name: "Cornstarch (for velvet coating)", amount: 1, unit: "tbsp" },
            { name: "Minced Ginger & Garlic", amount: 1.5, unit: "tbsp" },
            { name: "Green Scallions (sliced)", amount: 3, unit: "stalks" }
        ],
        instructions: [
            "Coat diced chicken with 1 tbsp soy sauce, cornstarch, and 1 tsp oil. Let sit for 10 minutes.",
            "Mix the sauce: Combine remaining soy sauce, rice vinegar, a teaspoon of sugar, sesame oil, and 2 tbsp water in a small bowl.",
            "Heat oil in a smoking-hot wok. Add dried chilies and Szechuan peppercorns; fry for 20 seconds until aromatic.",
            "Add marinated chicken in a single layer and sear for 3-4 minutes until golden and cooked through.",
            "Toss in ginger, garlic, bell pepper cubes, and white parts of scallions. Stir-fry rapidly for 1-2 minutes.",
            "Pour in the prepared sauce. Stir continuously until sauce thickens and coats the chicken gloriously.",
            "Fold in roasted peanuts and scallion greens. Serve over steamed jasmine rice."
        ],
        nutrition: {
            calories: "450 kcal",
            protein: "36g",
            carbs: "22g",
            fat: "24g",
            fiber: "3g"
        }
    },
    {
        id: 6,
        name: "Guacamole Street Tacos",
        tagline: "Charred corn tortillas loaded with black beans, roasted corn, fresh salsa, avocado, and lime.",
        cuisine: "Mexican",
        category: "Vegetarian",
        diet: "Vegan",
        time: 20,
        prepTime: 12,
        cookTime: 8,
        difficulty: "Easy",
        rating: 4.6,
        reviewsCount: 164,
        calories: 320,
        servings: 2,
        spicyLevel: 2,
        featured: false,
        popular: false,
        image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Sofia Gomez",
        ingredients: [
            { name: "Small Corn Tortillas", amount: 6, unit: "items" },
            { name: "Black Beans (rinsed & cooked)", amount: 1, unit: "can" },
            { name: "Sweet Corn Kernels (pan-charred)", amount: 0.5, unit: "cup" },
            { name: "Ripe Avocados (mashed)", amount: 2, unit: "items" },
            { name: "Diced Tomatoes & Red Onion", amount: 0.5, unit: "cup" },
            { name: "Fresh Cilantro & Lime wedges", amount: 1, unit: "bunch" },
            { name: "Cumin & Smoked Paprika", amount: 1, unit: "tsp" },
            { name: "Salt and Pepper", amount: 0.5, unit: "tsp" }
        ],
        instructions: [
            "In a skillet, warm black beans with cumin, paprika, salt, and 2 tbsp water for 3-4 minutes.",
            "In a dry skillet over high heat, blister the corn tortillas for 30 seconds on each side until warm and slightly charred.",
            "Make guacamole: Mash avocados with lime juice, diced onions, tomatoes, chopped cilantro, and salt.",
            "Assemble tacos: Spread a spoonful of guacamole onto each warm tortilla.",
            "Top with spiced black beans, charred sweet corn, and a drizzle of hot salsa.",
            "Garnish with fresh cilantro sprigs and squeeze generous fresh lime juice before biting."
        ],
        nutrition: {
            calories: "320 kcal",
            protein: "11g",
            carbs: "46g",
            fat: "14g",
            fiber: "9g"
        }
    },
    {
        id: 7,
        name: "Classic Paneer Butter Masala",
        tagline: "Soft cottage cheese cubes simmered in a silky, mildly spiced tomato, butter, and cashew gravy.",
        cuisine: "Indian",
        category: "Vegetarian",
        diet: "Vegetarian",
        time: 30,
        prepTime: 10,
        cookTime: 20,
        difficulty: "Easy",
        rating: 4.9,
        reviewsCount: 420,
        calories: 460,
        servings: 3,
        spicyLevel: 2,
        featured: true,
        popular: true,
        image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Sanjeev R.",
        ingredients: [
            { name: "Fresh Paneer (cubed)", amount: 250, unit: "g" },
            { name: "Ripe Tomatoes (pureed)", amount: 4, unit: "items" },
            { name: "Cashews (soaked & ground to paste)", amount: 12, unit: "nuts" },
            { name: "Butter", amount: 2, unit: "tbsp" },
            { name: "Fresh Cream", amount: 2, unit: "tbsp" },
            { name: "Ginger Garlic Paste", amount: 1, unit: "tbsp" },
            { name: "Kashmiri Chili Powder & Garam Masala", amount: 1.5, unit: "tsp" },
            { name: "Kasuri Methi (crushed fenugreek leaves)", amount: 1, unit: "tsp" },
            { name: "Sugar or Honey", amount: 0.5, unit: "tsp" },
            { name: "Salt", amount: 1, unit: "tsp" }
        ],
        instructions: [
            "Melt 1 tbsp butter in a pan, add ginger garlic paste and sauté until aroma blooms.",
            "Pour in the fresh tomato puree and cook on medium flame for 8-10 minutes until oil separates.",
            "Stir in Kashmiri chili powder, garam masala, salt, and the smooth cashew paste. Mix with 1/2 cup water.",
            "Simmer for 5 minutes until gravy becomes thick and glossy.",
            "Gently slide in fresh paneer cubes and let them absorb the flavors on low heat for 3 minutes.",
            "Finish with a spoon of butter, fresh cream, a pinch of sugar, and fragrant crushed kasuri methi.",
            "Serve hot with garlic butter naan or jeera rice."
        ],
        nutrition: {
            calories: "460 kcal",
            protein: "18g",
            carbs: "19g",
            fat: "34g",
            fiber: "3g"
        }
    },
    {
        id: 8,
        name: "Tokyo Teriyaki Salmon Bowl",
        tagline: "Pan-glazed Atlantic salmon fillet drizzled with homemade sweet teriyaki sauce over fluffy rice.",
        cuisine: "Japanese",
        category: "Non-Vegetarian",
        diet: "Pescatarian",
        time: 25,
        prepTime: 10,
        cookTime: 15,
        difficulty: "Easy",
        rating: 4.8,
        reviewsCount: 178,
        calories: 510,
        servings: 2,
        spicyLevel: 1,
        featured: false,
        popular: true,
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Kenji Tanaka",
        ingredients: [
            { name: "Salmon Fillets (skin-on)", amount: 2, unit: "fillets" },
            { name: "Soy Sauce", amount: 3, unit: "tbsp" },
            { name: "Mirin or Rice Vinegar", amount: 2, unit: "tbsp" },
            { name: "Honey or Brown Sugar", amount: 1.5, unit: "tbsp" },
            { name: "Grated Ginger & Minced Garlic", amount: 1, unit: "tsp" },
            { name: "Steamed Japanese Short Grain Rice", amount: 2, unit: "bowls" },
            { name: "Steamed Broccoli & Edamame", amount: 1, unit: "cup" },
            { name: "Toasted Sesame Seeds", amount: 1, unit: "tsp" }
        ],
        instructions: [
            "Whisk soy sauce, mirin, honey, grated ginger, and garlic in a small saucepan over low heat for 3 minutes until thickened into a glaze.",
            "Pat salmon dry and season lightly with salt and pepper.",
            "Heat 1 tbsp oil in a non-stick skillet over medium-high heat. Place salmon skin-side down and cook for 4-5 minutes until crispy.",
            "Flip the salmon and cook the other side for 3 minutes.",
            "Pour the teriyaki sauce directly into the pan, spooning the bubbly glaze over the salmon for 1 minute.",
            "Assemble bowls with steamed rice, steamed broccoli florets, and edamame.",
            "Place glazed salmon on top, drizzle remaining glaze, and sprinkle toasted sesame seeds."
        ],
        nutrition: {
            calories: "510 kcal",
            protein: "34g",
            carbs: "52g",
            fat: "17g",
            fiber: "4g"
        }
    },
    {
        id: 9,
        name: "Mediterranean Greek Salad & Hummus",
        tagline: "Crisp cucumbers, kalamata olives, heirloom tomatoes, and creamy feta paired with silky olive hummus.",
        cuisine: "Mediterranean",
        category: "Vegetarian",
        diet: "Vegetarian",
        time: 15,
        prepTime: 15,
        cookTime: 0,
        difficulty: "Easy",
        rating: 4.7,
        reviewsCount: 142,
        calories: 340,
        servings: 2,
        spicyLevel: 1,
        featured: false,
        popular: false,
        image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Elena Costa",
        ingredients: [
            { name: "Heirloom or Cherry Tomatoes (halved)", amount: 2, unit: "cups" },
            { name: "English Cucumber (diced)", amount: 1, unit: "large" },
            { name: "Kalamata Olives (pitted)", amount: 0.3, unit: "cup" },
            { name: "Greek Feta Cheese block (crumbled)", amount: 100, unit: "g" },
            { name: "Red Onion (thinly sliced)", amount: 0.5, unit: "item" },
            { name: "Extra Virgin Olive Oil", amount: 2, unit: "tbsp" },
            { name: "Red Wine Vinegar", amount: 1, unit: "tbsp" },
            { name: "Dried Wild Oregano", amount: 1, unit: "tsp" },
            { name: "Warm Pita Bread & Hummus", amount: 2, unit: "servings" }
        ],
        instructions: [
            "In a large bowl, combine chopped tomatoes, diced cucumber, sliced red onion, and kalamata olives.",
            "In a small ramekin, whisk together extra virgin olive oil, red wine vinegar, dried oregano, salt, and cracked black pepper.",
            "Pour dressing over vegetables and toss gently to coat.",
            "Top with big crumbles of fresh Greek feta cheese and another pinch of oregano.",
            "Spread velvety hummus on a serving platter and arrange salad alongside warm, sliced pita wedges."
        ],
        nutrition: {
            calories: "340 kcal",
            protein: "10g",
            carbs: "30g",
            fat: "21g",
            fiber: "6g"
        }
    },
    {
        id: 10,
        name: "Authentic Thai Green Chicken Curry",
        tagline: "Aromatic coconut milk curry infused with green chilies, lemongrass, bamboo shoots & kaffir lime.",
        cuisine: "Thai",
        category: "Non-Vegetarian",
        diet: "Non-Vegetarian",
        time: 30,
        prepTime: 12,
        cookTime: 18,
        difficulty: "Medium",
        rating: 4.9,
        reviewsCount: 260,
        calories: 520,
        servings: 3,
        spicyLevel: 3,
        featured: true,
        popular: true,
        image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Anong P.",
        ingredients: [
            { name: "Chicken Breast / Thighs (thinly sliced)", amount: 450, unit: "g" },
            { name: "Thai Green Curry Paste", amount: 3, unit: "tbsp" },
            { name: "Full-Fat Coconut Milk", amount: 1, unit: "can (400ml)" },
            { name: "Bamboo Shoots (sliced)", amount: 0.5, unit: "cup" },
            { name: "Thai Eggplants or Zucchini (sliced)", amount: 1, unit: "cup" },
            { name: "Fish Sauce (or Soy Sauce)", amount: 1.5, unit: "tbsp" },
            { name: "Palm Sugar or Brown Sugar", amount: 1, unit: "tsp" },
            { name: "Kaffir Lime Leaves (torn)", amount: 4, unit: "leaves" },
            { name: "Fresh Thai Basil Leaves", amount: 1, unit: "cup" }
        ],
        instructions: [
            "Skim 3 tbsp of the thick coconut cream from the top of the can into a hot wok or pot over medium heat.",
            "Add the green curry paste and fry for 2-3 minutes until oil separates and aroma is released.",
            "Add the sliced chicken pieces and stir-fry until the exterior turns opaque (about 3 minutes).",
            "Pour in the remaining coconut milk and 1/4 cup water or broth. Bring to a gentle boil.",
            "Add bamboo shoots, sliced eggplant/zucchini, and torn kaffir lime leaves. Simmer for 8-10 minutes until chicken is tender.",
            "Season with fish sauce and palm sugar. Adjust seasoning to strike a balance between spicy, savory, and sweet.",
            "Turn off heat and fold in fresh Thai basil leaves until wilted. Serve with fragrant Jasmine rice."
        ],
        nutrition: {
            calories: "520 kcal",
            protein: "32g",
            carbs: "14g",
            fat: "38g",
            fiber: "3g"
        }
    },
    {
        id: 11,
        name: "Smoky BBQ Loaded Bacon Burger",
        tagline: "Juicy beef patty grilled to perfection, stacked with smoked cheddar, crispy bacon, and onion rings.",
        cuisine: "American",
        category: "Non-Vegetarian",
        diet: "Non-Vegetarian",
        time: 25,
        prepTime: 10,
        cookTime: 15,
        difficulty: "Easy",
        rating: 4.8,
        reviewsCount: 350,
        calories: 780,
        servings: 2,
        spicyLevel: 1,
        featured: false,
        popular: true,
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Jack Miller",
        ingredients: [
            { name: "Ground Beef Patty (80/20 blend)", amount: 2, unit: "patties" },
            { name: "Brioche Burger Buns", amount: 2, unit: "buns" },
            { name: "Smoked Cheddar Cheese slices", amount: 2, unit: "slices" },
            { name: "Crispy Bacon strips", amount: 4, unit: "strips" },
            { name: "Crispy Onion Rings or Caramelized Onions", amount: 0.5, unit: "cup" },
            { name: "Smoky BBQ Sauce", amount: 3, unit: "tbsp" },
            { name: "Lettuce leaves & Tomato slices", amount: 2, unit: "servings" },
            { name: "Butter for toasting", amount: 1, unit: "tbsp" }
        ],
        instructions: [
            "Preheat a cast-iron skillet or grill over medium-high heat. Cook bacon strips until crisp, then set aside.",
            "Season beef patties generously with salt, garlic powder, and coarse black pepper.",
            "Place patties in the hot skillet. Sear for 4 minutes without moving to develop a deep golden crust.",
            "Flip patties, immediately top each with a slice of smoked cheddar cheese, and cover with a lid for 2 minutes to melt.",
            "Butter and toast the brioche buns on the griddle until golden.",
            "Spread BBQ sauce on bottom bun, add lettuce and tomato, place the cheesy patty, top with bacon and crispy onion rings.",
            "Crown with the top bun and serve with french fries."
        ],
        nutrition: {
            calories: "780 kcal",
            protein: "44g",
            carbs: "50g",
            fat: "46g",
            fiber: "3g"
        }
    },
    {
        id: 12,
        name: "Avocado Toast with Poached Egg",
        tagline: "Crunchy sourdough toast layered with seasoned mashed avocado, soft poached eggs & everything bagel spice.",
        cuisine: "American",
        category: "Vegetarian",
        diet: "Vegetarian",
        time: 15,
        prepTime: 5,
        cookTime: 10,
        difficulty: "Easy",
        rating: 4.6,
        reviewsCount: 180,
        calories: 380,
        servings: 2,
        spicyLevel: 1,
        featured: false,
        popular: false,
        image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Chloe Vance",
        ingredients: [
            { name: "Thick Artisan Sourdough Slices", amount: 2, unit: "slices" },
            { name: "Ripe Avocados", amount: 2, unit: "items" },
            { name: "Fresh Eggs", amount: 2, unit: "items" },
            { name: "Lemon Juice", amount: 1, unit: "tbsp" },
            { name: "Red Pepper Flakes & Everything Bagel Seasoning", amount: 1, unit: "tsp" },
            { name: "Microgreens & Radish slices for garnish", amount: 2, unit: "tbsp" },
            { name: "Extra Virgin Olive Oil", amount: 1, unit: "tsp" },
            { name: "Salt and Pepper", amount: 0.5, unit: "tsp" }
        ],
        instructions: [
            "Toast sourdough slices until deeply crisp and golden.",
            "In a small bowl, roughly mash the avocados with lemon juice, salt, pepper, and a drizzle of olive oil.",
            "Bring a small pot of water to a gentle simmer with 1 tsp white vinegar. Swirl to create a whirlpool.",
            "Crack egg into a small cup, slide gently into whirlpool center, and poach for exactly 3 minutes for a runny yolk.",
            "Generously spread avocado mash over toasted sourdough.",
            "Carefully rest a poached egg onto each toast.",
            "Sprinkle with everything seasoning, chili flakes, and fresh microgreens."
        ],
        nutrition: {
            calories: "380 kcal",
            protein: "14g",
            carbs: "34g",
            fat: "22g",
            fiber: "8g"
        }
    },
    {
        id: 13,
        name: "Hearty Chickpea & Veggie Buddha Bowl",
        tagline: "Vibrant bowl loaded with crispy spiced chickpeas, quinoa, roasted sweet potatoes, and creamy tahini.",
        cuisine: "Mediterranean",
        category: "Vegetarian",
        diet: "Vegan",
        time: 30,
        prepTime: 10,
        cookTime: 20,
        difficulty: "Easy",
        rating: 4.8,
        reviewsCount: 155,
        calories: 420,
        servings: 2,
        spicyLevel: 1,
        featured: false,
        popular: true,
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Maya Patel",
        ingredients: [
            { name: "Cooked Quinoa", amount: 2, unit: "cups" },
            { name: "Chickpeas (drained & patted dry)", amount: 1, unit: "can (400g)" },
            { name: "Sweet Potato (cubed)", amount: 1, unit: "medium" },
            { name: "Kale or Baby Spinach", amount: 2, unit: "cups" },
            { name: "Tahini (sesame paste)", amount: 2, unit: "tbsp" },
            { name: "Lemon Juice & Maple Syrup", amount: 1, unit: "tbsp" },
            { name: "Smoked Paprika & Cumin", amount: 1, unit: "tsp" },
            { name: "Olive Oil", amount: 2, unit: "tbsp" }
        ],
        instructions: [
            "Toss cubed sweet potatoes and chickpeas in 1 tbsp olive oil, smoked paprika, cumin, and salt.",
            "Roast in oven or air-fryer at 200°C (400°F) for 20 minutes until sweet potatoes are tender and chickpeas are crunchy.",
            "Whisk tahini, lemon juice, maple syrup, warm water (to thin), and salt into a smooth pourable dressing.",
            "Divide cooked fluffy quinoa into two bowls.",
            "Arrange roasted sweet potatoes, crispy chickpeas, fresh shredded kale, and avocado slices in vibrant sections.",
            "Drizzle creamy tahini dressing generously over the top and serve warm."
        ],
        nutrition: {
            calories: "420 kcal",
            protein: "15g",
            carbs: "64g",
            fat: "14g",
            fiber: "11g"
        }
    },
    {
        id: 14,
        name: "Authentic Mexican Enchiladas Suizas",
        tagline: "Shredded chicken wrapped in corn tortillas, drenched in creamy roasted tomatillo salsa and melted cheese.",
        cuisine: "Mexican",
        category: "Non-Vegetarian",
        diet: "Non-Vegetarian",
        time: 40,
        prepTime: 15,
        cookTime: 25,
        difficulty: "Medium",
        rating: 4.9,
        reviewsCount: 220,
        calories: 590,
        servings: 4,
        spicyLevel: 3,
        featured: false,
        popular: false,
        image: "https://images.unsplash.com/photo-1534352956036-cd81e27dd615?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Sofia Gomez",
        ingredients: [
            { name: "Corn Tortillas", amount: 8, unit: "items" },
            { name: "Cooked Shredded Chicken", amount: 3, unit: "cups" },
            { name: "Tomatillos (husked & roasted)", amount: 6, unit: "items" },
            { name: "Serrano or Jalapeño Pepper", amount: 2, unit: "items" },
            { name: "Mexican Crema or Sour Cream", amount: 0.5, unit: "cup" },
            { name: "Monterey Jack or Oaxaca Cheese (shredded)", amount: 1.5, unit: "cups" },
            { name: "Cilantro & Onion", amount: 0.5, unit: "cup" },
            { name: "Garlic & Salt", amount: 1, unit: "tsp" }
        ],
        instructions: [
            "Roast tomatillos, serrano peppers, and garlic under broiler until charred. Blend with fresh cilantro, crema, and salt into a smooth salsa verde.",
            "Briefly warm tortillas in a skillet with a drop of oil so they become pliable.",
            "Fill each warm tortilla with shredded chicken, roll tightly, and arrange seam-side down in a baking dish.",
            "Pour the velvety salsa verde evenly over the enchiladas.",
            "Smother with shredded Monterey Jack / Oaxaca cheese.",
            "Bake at 190°C (375°F) for 20 minutes until bubbling and lightly golden on top.",
            "Garnish with chopped cilantro and sliced red onions."
        ],
        nutrition: {
            calories: "590 kcal",
            protein: "39g",
            carbs: "38g",
            fat: "32g",
            fiber: "4g"
        }
    },
    {
        id: 15,
        name: "Authentic Chinese Vegetable Chow Mein",
        tagline: "Wok-tossed egg noodles with crisp cabbage, bell peppers, carrots, bean sprouts & savory soy sauce.",
        cuisine: "Chinese",
        category: "Vegetarian",
        diet: "Vegetarian",
        time: 18,
        prepTime: 10,
        cookTime: 8,
        difficulty: "Easy",
        rating: 4.7,
        reviewsCount: 168,
        calories: 390,
        servings: 2,
        spicyLevel: 1,
        featured: false,
        popular: true,
        image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Wei Chen",
        ingredients: [
            { name: "Chow Mein or Egg Noodles", amount: 250, unit: "g" },
            { name: "Shredded Green Cabbage", amount: 1.5, unit: "cups" },
            { name: "Carrots (julienned)", amount: 1, unit: "item" },
            { name: "Bell Pepper (sliced thin)", amount: 1, unit: "item" },
            { name: "Fresh Bean Sprouts", amount: 1, unit: "cup" },
            { name: "Garlic & Ginger (minced)", amount: 1.5, unit: "tbsp" },
            { name: "Soy Sauce (Dark & Light)", amount: 2, unit: "tbsp" },
            { name: "Oyster or Vegetarian Mushroom Sauce", amount: 1, unit: "tbsp" },
            { name: "Sesame Oil", amount: 1, unit: "tsp" }
        ],
        instructions: [
            "Cook noodles in boiling water for 3 minutes until just tender, rinse with cold water, and toss with a few drops of oil.",
            "In a small bowl, whisk light soy sauce, dark soy sauce, vegetarian stir-fry sauce, and sesame oil.",
            "Heat 2 tbsp oil in a wok over high heat. Add minced ginger and garlic; stir-fry for 15 seconds.",
            "Add shredded cabbage, carrots, and bell peppers. Stir-fry aggressively for 2 minutes to retain crunch.",
            "Toss in cooked noodles, bean sprouts, and pour sauce around the edge of the wok.",
            "Toss continuously with tongs for 2 minutes until noodles absorb sauce and take on smoky wok flavor.",
            "Serve hot with chili oil or toasted sesame seeds."
        ],
        nutrition: {
            calories: "390 kcal",
            protein: "11g",
            carbs: "62g",
            fat: "12g",
            fiber: "5g"
        }
    },
    {
        id: 16,
        name: "Fresh Strawberry Basil Smoothie Bowl",
        tagline: "Thick blended frozen berries, acai, Greek yogurt, topped with chia seeds, banana slices & crunchy granola.",
        cuisine: "American",
        category: "Vegetarian",
        diet: "Vegetarian",
        time: 10,
        prepTime: 10,
        cookTime: 0,
        difficulty: "Easy",
        rating: 4.8,
        reviewsCount: 130,
        calories: 290,
        servings: 1,
        spicyLevel: 1,
        featured: false,
        popular: false,
        image: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Chloe Vance",
        ingredients: [
            { name: "Frozen Strawberries & Blueberries", amount: 1.5, unit: "cups" },
            { name: "Frozen Banana", amount: 1, unit: "item" },
            { name: "Greek Yogurt (or Almond Milk)", amount: 0.5, unit: "cup" },
            { name: "Honey or Maple Syrup", amount: 1, unit: "tbsp" },
            { name: "Crunchy Granola", amount: 3, unit: "tbsp" },
            { name: "Chia Seeds", amount: 1, unit: "tsp" },
            { name: "Fresh Basil & Fresh Berries for topping", amount: 0.25, unit: "cup" }
        ],
        instructions: [
            "Add frozen strawberries, frozen banana, Greek yogurt, and honey into a high-speed blender.",
            "Blend on low, pushing ingredients down with a tamper, until smooth, ultra-thick, and creamy like soft serve.",
            "Scoop the smoothie into a shallow wide bowl.",
            "Artfully arrange sliced fresh strawberries, blueberries, crunchy granola, and chia seeds in rows.",
            "Garnish with a tiny fresh basil leaf and enjoy immediately with a spoon."
        ],
        nutrition: {
            calories: "290 kcal",
            protein: "12g",
            carbs: "52g",
            fat: "4g",
            fiber: "8g"
        }
    },

    /* ==========================================================================
       Traditional & Heritage World Recipes
       ========================================================================== */
    {
        id: 17,
        name: "Traditional South Indian Sambar & Steamed Idli",
        tagline: "Fluffy steamed fermented rice cakes served with aromatic toor dal lentil vegetable sambar and coconut chutney.",
        cuisine: "Indian",
        category: "Vegetarian",
        diet: "Vegetarian",
        time: 40,
        prepTime: 15,
        cookTime: 25,
        difficulty: "Medium",
        rating: 4.9,
        reviewsCount: 380,
        calories: 330,
        servings: 4,
        spicyLevel: 2,
        featured: true,
        popular: true,
        image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Meenakshi Sundaram",
        ingredients: [
            { name: "Fermented Idli Batter", amount: 3, unit: "cups" },
            { name: "Toor Dal (split pigeon peas)", amount: 1, unit: "cup" },
            { name: "Shallots / Pearl Onions", amount: 10, unit: "items" },
            { name: "Drumstick & Carrots (cut into 2-inch pieces)", amount: 1.5, unit: "cups" },
            { name: "Tamarind Pulp (extracted in warm water)", amount: 3, unit: "tbsp" },
            { name: "Traditional Sambar Powder", amount: 2, unit: "tbsp" },
            { name: "Mustard Seeds & Fenugreek Seeds", amount: 1, unit: "tsp" },
            { name: "Curry Leaves & Dry Red Chilies", amount: 2, unit: "stalks" },
            { name: "Hing (Asafoetida)", amount: 0.25, unit: "tsp" },
            { name: "Sesame Oil / Ghee", amount: 1.5, unit: "tbsp" },
            { name: "Salt", amount: 1.5, unit: "tsp" }
        ],
        instructions: [
            "Grease idli molds with sesame oil. Pour idli batter and steam in an idli steamer for 10-12 minutes until fluffy. Unmold with a wet spoon.",
            "Pressure cook toor dal with turmeric and 2.5 cups water until soft and mushy; mash lightly with a whisk.",
            "In a pot, boil shallots, drumstick, and carrots with tamarind water, sambar powder, turmeric, and salt until vegetables are tender.",
            "Add the mashed cooked dal into the pot, adjust consistency with water, and bring to a rolling boil for 5 minutes.",
            "Prepare tempering (Tadka): Heat ghee in a small pan, crackle mustard seeds, fenugreek, dried red chilies, curry leaves, and a generous pinch of asafoetida.",
            "Pour hot aromatic tempering over the simmering sambar and immediately cover with a lid to trap the aromas.",
            "Serve steaming soft idlis submerged in hot sambar with freshly ground coconut chutney."
        ],
        nutrition: {
            calories: "330 kcal",
            protein: "14g",
            carbs: "62g",
            fat: "5g",
            fiber: "8g"
        }
    },
    {
        id: 18,
        name: "Authentic Delhi Butter Chicken (Murgh Makhani)",
        tagline: "Original tandoori marinated chicken simmered in velvety tomato, makhani butter, cashew cream, and fenugreek gravy.",
        cuisine: "Indian",
        category: "Non-Vegetarian",
        diet: "Non-Vegetarian",
        time: 45,
        prepTime: 20,
        cookTime: 25,
        difficulty: "Medium",
        rating: 5.0,
        reviewsCount: 520,
        calories: 650,
        servings: 4,
        spicyLevel: 2,
        featured: true,
        popular: true,
        image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Sanjeev R.",
        ingredients: [
            { name: "Boneless Chicken Thighs (cubed)", amount: 600, unit: "g" },
            { name: "Hung Curd / Greek Yogurt", amount: 0.5, unit: "cup" },
            { name: "Kashmiri Red Chili Powder", amount: 2, unit: "tbsp" },
            { name: "Ginger-Garlic Paste", amount: 2, unit: "tbsp" },
            { name: "Ripe Red Tomatoes (pureed)", amount: 6, unit: "large" },
            { name: "Cashews (boiled & blended to smooth paste)", amount: 15, unit: "nuts" },
            { name: "Unsalted Butter (Makhani)", amount: 3, unit: "tbsp" },
            { name: "Heavy Cooking Cream", amount: 3, unit: "tbsp" },
            { name: "Kasuri Methi (roasted & crushed)", amount: 1.5, unit: "tsp" },
            { name: "Garam Masala & Cardamom Powder", amount: 1, unit: "tsp" },
            { name: "Honey or Sugar", amount: 1, unit: "tsp" }
        ],
        instructions: [
            "Marinate chicken in yogurt, ginger-garlic paste, 1 tbsp Kashmiri chili, garam masala, mustard oil, and salt for 1 hour.",
            "Sear the chicken on high heat in a skillet or grill until lightly charred and smoky (about 8 minutes). Set aside.",
            "For Makhani Gravy: Simmer tomato puree with whole cardamom, cloves, and remaining Kashmiri chili powder until reduced and deep crimson.",
            "Blend the tomato reduction until silky smooth, strain back into the pan, and stir in the rich cashew paste.",
            "Add butter, heavy cream, honey, and crushed kasuri methi. Simmer until glossy.",
            "Gently slide in the smoky grilled chicken pieces and cook on low heat for 6-8 minutes.",
            "Drizzle with swirl of cream and serve with hot garlic naan or saffron pulao."
        ],
        nutrition: {
            calories: "650 kcal",
            protein: "42g",
            carbs: "18g",
            fat: "46g",
            fiber: "3g"
        }
    },
    {
        id: 19,
        name: "Traditional Spanish Seafood Paella Valenciana",
        tagline: "Authentic saffron-infused Bomba rice loaded with juicy king prawns, fresh mussels, calamari & rosemary.",
        cuisine: "Mediterranean",
        category: "Non-Vegetarian",
        diet: "Pescatarian",
        time: 45,
        prepTime: 15,
        cookTime: 30,
        difficulty: "Hard",
        rating: 4.9,
        reviewsCount: 290,
        calories: 560,
        servings: 4,
        spicyLevel: 1,
        featured: true,
        popular: true,
        image: "https://images.unsplash.com/photo-1534080564583-6be75777b70a?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Mateo Alarcón",
        ingredients: [
            { name: "Spanish Bomba or Calasparra Rice", amount: 2, unit: "cups" },
            { name: "Tiger Prawns / Shrimp (shell on)", amount: 300, unit: "g" },
            { name: "Fresh Mussels (scrubbed & debearded)", amount: 250, unit: "g" },
            { name: "Calamari Rings (squid)", amount: 200, unit: "g" },
            { name: "Seafood or Fish Broth (infused with saffron)", amount: 4, unit: "cups" },
            { name: "Spanish Saffron threads", amount: 0.5, unit: "tsp" },
            { name: "Sweet Smoked Spanish Paprika (Pimentón)", amount: 1.5, unit: "tsp" },
            { name: "Grated Tomatoes & Minced Garlic", amount: 0.5, unit: "cup" },
            { name: "Red Bell Pepper (sliced into strips)", amount: 1, unit: "item" },
            { name: "Extra Virgin Olive Oil", amount: 3, unit: "tbsp" },
            { name: "Fresh Lemon wedges & Rosemary sprig", amount: 1, unit: "serving" }
        ],
        instructions: [
            "Warm seafood broth in a small pot and steep saffron threads for 10 minutes until deep golden-amber.",
            "Heat olive oil in a wide, shallow paella pan. Sear prawns and calamari for 2 minutes, then remove and set aside.",
            "In the same pan, sauté bell pepper strips and minced garlic, then add grated tomato paste and smoked paprika (Sofrito).",
            "Pour in the Bomba rice and toast for 2 minutes, stirring to coat every grain with the rich sofrito oils.",
            "Pour in all the saffron-infused broth. Bring to a vigorous boil, then lower heat to gentle simmer. DO NOT stir from this point onwards.",
            "After 12 minutes, arrange prawns, calamari, and mussels into the rice. Cook for another 8 minutes until mussels open.",
            "Increase heat to medium-high for the last 2 minutes to create the legendary caramelized crispy bottom crust (Socarrat).",
            "Rest covered with a clean tea towel for 5 minutes, garnish with lemon wedges, and serve straight from the pan."
        ],
        nutrition: {
            calories: "560 kcal",
            protein: "36g",
            carbs: "68g",
            fat: "16g",
            fiber: "4g"
        }
    },
    {
        id: 20,
        name: "Traditional Tokyo Shoyu Ramen with Chashu",
        tagline: "Handcrafted springy ramen noodles in a rich umami dashi broth with melt-in-mouth chashu pork, soft ajitsuke egg, and nori.",
        cuisine: "Japanese",
        category: "Non-Vegetarian",
        diet: "Non-Vegetarian",
        time: 50,
        prepTime: 20,
        cookTime: 30,
        difficulty: "Medium",
        rating: 4.9,
        reviewsCount: 315,
        calories: 590,
        servings: 2,
        spicyLevel: 1,
        featured: true,
        popular: true,
        image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Kenji Tanaka",
        ingredients: [
            { name: "Fresh Ramen Noodles", amount: 2, unit: "portions" },
            { name: "Rich Chicken & Dashi Broth", amount: 4, unit: "cups" },
            { name: "Braised Chashu Pork slices", amount: 6, unit: "slices" },
            { name: "Ajitsuke Tamago (soft ramen eggs, halved)", amount: 2, unit: "eggs" },
            { name: "Shoyu Tare (Japanese soy sauce seasoning blend)", amount: 4, unit: "tbsp" },
            { name: "Menma (seasoned bamboo shoots)", amount: 0.25, unit: "cup" },
            { name: "Green Scallions (finely sliced)", amount: 3, unit: "stalks" },
            { name: "Crispy Nori Seaweed sheets", amount: 2, unit: "sheets" },
            { name: "Aroma Sesame & Garlic Oil (Mayu)", amount: 1, unit: "tbsp" }
        ],
        instructions: [
            "Bring the dashi and chicken broth to a gentle simmer in a soup pot.",
            "In each serving ramen bowl, add 2 tbsp of shoyu tare and 1 tsp aroma oil.",
            "Cook fresh ramen noodles in a pot of rolling boiling water for exactly 90 seconds (firm al dente). Drain vigorously.",
            "Ladle piping hot broth into the serving bowls and whisk briefly with the tare base.",
            "Fold the noodles gracefully into the broth using chopsticks.",
            "Top with tender braised chashu pork slices, seasoned bamboo shoots, half-cut jammy ramen egg, and green scallions.",
            "Tuck crispy nori sheets on the rim of the bowl and serve immediately while steaming hot."
        ],
        nutrition: {
            calories: "590 kcal",
            protein: "34g",
            carbs: "66g",
            fat: "21g",
            fiber: "4g"
        }
    },
    {
        id: 21,
        name: "Traditional Middle Eastern Shakshuka",
        tagline: "Farm fresh eggs gently poached in a spiced, bubbling skillet of roasted bell peppers, tomatoes, garlic, cumin, and feta.",
        cuisine: "Mediterranean",
        category: "Vegetarian",
        diet: "Vegetarian",
        time: 25,
        prepTime: 10,
        cookTime: 15,
        difficulty: "Easy",
        rating: 4.8,
        reviewsCount: 240,
        calories: 340,
        servings: 2,
        spicyLevel: 2,
        featured: false,
        popular: true,
        image: "https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Omar Haddad",
        ingredients: [
            { name: "Fresh Eggs", amount: 4, unit: "items" },
            { name: "Crushed San Marzano Tomatoes", amount: 1, unit: "can (400g)" },
            { name: "Red Bell Pepper (diced)", amount: 1, unit: "large" },
            { name: "Onion & Garlic cloves (minced)", amount: 4, unit: "cloves" },
            { name: "Ground Cumin & Smoked Paprika", amount: 1.5, unit: "tsp" },
            { name: "Harissa Paste or Chili Flakes", amount: 1, unit: "tsp" },
            { name: "Crumbled Feta Cheese", amount: 60, unit: "g" },
            { name: "Extra Virgin Olive Oil", amount: 2, unit: "tbsp" },
            { name: "Fresh Cilantro & Parsley", amount: 0.25, unit: "cup" },
            { name: "Crusty Bread or Challah for dipping", amount: 2, unit: "servings" }
        ],
        instructions: [
            "Heat extra virgin olive oil in a heavy cast-iron skillet over medium heat.",
            "Add diced onions and red bell peppers; cook for 5 minutes until soft and caramelized around edges.",
            "Stir in minced garlic, ground cumin, smoked paprika, and harissa paste; fry for 1 minute until fragrant.",
            "Pour in crushed tomatoes and season with salt and pepper. Simmer for 8 minutes until sauce is thick and rich.",
            "Use a spoon to create 4 small wells in the sauce. Crack an egg directly into each well.",
            "Cover the skillet and cook on low heat for 5-6 minutes until egg whites are set but yolks remain gloriously runny.",
            "Sprinkle with crumbled feta cheese and chopped fresh parsley and cilantro.",
            "Serve right in the sizzling skillet with thick slices of warm crusty bread."
        ],
        nutrition: {
            calories: "340 kcal",
            protein: "19g",
            carbs: "18g",
            fat: "22g",
            fiber: "5g"
        }
    },
    {
        id: 22,
        name: "Traditional Italian Tagliatelle al Ragù Bolognese",
        tagline: "Slow-simmered heritage meat ragù with mirepoix, red wine, tomatoes & whole milk over golden fresh tagliatelle.",
        cuisine: "Italian",
        category: "Non-Vegetarian",
        diet: "Non-Vegetarian",
        time: 60,
        prepTime: 20,
        cookTime: 40,
        difficulty: "Medium",
        rating: 4.9,
        reviewsCount: 390,
        calories: 610,
        servings: 4,
        spicyLevel: 1,
        featured: true,
        popular: true,
        image: "https://images.unsplash.com/photo-1621996346565-e3d5d6281699?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Marco V.",
        ingredients: [
            { name: "Fresh Tagliatelle Pasta (egg pasta)", amount: 400, unit: "g" },
            { name: "Coarsely Ground Beef & Pork (blend)", amount: 500, unit: "g" },
            { name: "Finely Minced Onion, Celery & Carrot (Soffritto)", amount: 1.5, unit: "cups" },
            { name: "Pancetta (finely diced)", amount: 60, unit: "g" },
            { name: "Dry Italian Red Wine (Chianti)", amount: 0.5, unit: "cup" },
            { name: "Whole Milk", amount: 0.5, unit: "cup" },
            { name: "Tomato Paste & Passata", amount: 1.5, unit: "cups" },
            { name: "Beef Broth", amount: 1, unit: "cup" },
            { name: "Parmigiano-Reggiano (freshly grated)", amount: 0.5, unit: "cup" },
            { name: "Butter & Olive Oil", amount: 2, unit: "tbsp" }
        ],
        instructions: [
            "In a heavy Dutch oven, render diced pancetta in 1 tbsp olive oil over medium heat.",
            "Add the soffritto (onion, celery, carrot) and sauté gently for 10 minutes until tender and sweet.",
            "Add ground meat, breaking up with a spoon, and brown thoroughly until moisture evaporates.",
            "Pour in the red wine and let it bubble and reduce completely to infuse deep flavor.",
            "Add the whole milk and a pinch of nutmeg, simmering until milk is absorbed (this makes the meat extraordinarily tender).",
            "Stir in tomato paste, passata, and warm broth. Cover and simmer on the lowest heat for at least 35-40 minutes.",
            "Cook fresh egg tagliatelle in salted boiling water for 2-3 minutes until al dente.",
            "Toss the hot pasta directly into the rich ragù with a knob of butter and generous Parmigiano-Reggiano."
        ],
        nutrition: {
            calories: "610 kcal",
            protein: "38g",
            carbs: "56g",
            fat: "26g",
            fiber: "4g"
        }
    },
    {
        id: 23,
        name: "Traditional Mexican Chicken Pozole Rojo",
        tagline: "Ancient Aztec heritage hominy stew simmered with shredded chicken in a rich ancho & guajillo chili broth.",
        cuisine: "Mexican",
        category: "Non-Vegetarian",
        diet: "Non-Vegetarian",
        time: 55,
        prepTime: 20,
        cookTime: 35,
        difficulty: "Medium",
        rating: 4.8,
        reviewsCount: 205,
        calories: 460,
        servings: 4,
        spicyLevel: 3,
        featured: false,
        popular: true,
        image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Sofia Gomez",
        ingredients: [
            { name: "Shredded Chicken Breast / Thighs", amount: 500, unit: "g" },
            { name: "White Hominy (Maíz Pozolero, rinsed & drained)", amount: 1, unit: "large can (800g)" },
            { name: "Dried Ancho Chilies (stemmed & seeded)", amount: 3, unit: "items" },
            { name: "Dried Guajillo Chilies (stemmed & seeded)", amount: 3, unit: "items" },
            { name: "Chicken Broth", amount: 5, unit: "cups" },
            { name: "Garlic cloves & White Onion", amount: 5, unit: "cloves" },
            { name: "Mexican Oregano & Ground Cumin", amount: 1.5, unit: "tsp" },
            { name: "Shredded Cabbage, Radishes & Limes for garnish", amount: 2, unit: "cups" },
            { name: "Crispy Corn Tostadas", amount: 4, unit: "items" }
        ],
        instructions: [
            "Toast dried ancho and guajillo chilies in a dry pan for 1-2 minutes until fragrant, then soak in hot water for 15 minutes to soften.",
            "Transfer softened chilies, garlic, half an onion, oregano, cumin, and 1 cup of soaking water into a blender. Blend until super smooth, then strain through a mesh sieve.",
            "In a large soup pot, heat 1 tbsp oil, pour the strained red chili sauce, and fry for 4 minutes until dark and fragrant.",
            "Pour in the rich chicken broth and bring to a boil.",
            "Add the rinsed white hominy and simmer for 20 minutes to absorb the complex chili flavors.",
            "Stir in the shredded chicken and cook on low for an additional 10 minutes. Season with sea salt.",
            "Ladle hot pozole into bowls and top with shredded crunchy cabbage, thinly sliced radishes, a sprinkle of Mexican oregano, and fresh lime wedges."
        ],
        nutrition: {
            calories: "460 kcal",
            protein: "38g",
            carbs: "48g",
            fat: "12g",
            fiber: "9g"
        }
    },
    {
        id: 24,
        name: "Traditional Chinese Steamed Pork & Scallion Dumplings (Jiaozi)",
        tagline: "Handcrafted tender wrappers filled with juicy seasoned pork, fresh ginger, scallions, and served with black vinegar chili dip.",
        cuisine: "Chinese",
        category: "Non-Vegetarian",
        diet: "Non-Vegetarian",
        time: 40,
        prepTime: 25,
        cookTime: 15,
        difficulty: "Medium",
        rating: 4.9,
        reviewsCount: 310,
        calories: 390,
        servings: 3,
        spicyLevel: 1,
        featured: false,
        popular: true,
        image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Wei Chen",
        ingredients: [
            { name: "Round Dumpling Wrappers (Jiaozi skin)", amount: 24, unit: "wrappers" },
            { name: "Ground Pork (or minced chicken)", amount: 350, unit: "g" },
            { name: "Finely Chopped Scallions", amount: 4, unit: "stalks" },
            { name: "Fresh Ginger (grated)", amount: 1.5, unit: "tbsp" },
            { name: "Chinese Shaoxing Cooking Wine", amount: 1, unit: "tbsp" },
            { name: "Light Soy Sauce & Toasted Sesame Oil", amount: 2, unit: "tbsp" },
            { name: "White Pepper & Salt", amount: 0.5, unit: "tsp" },
            { name: "Chinese Chinkiang Black Vinegar & Chili Oil for dip", amount: 3, unit: "tbsp" }
        ],
        instructions: [
            "In a mixing bowl, combine ground pork, grated ginger, chopped scallions, soy sauce, Shaoxing wine, sesame oil, white pepper, and salt.",
            "Stir the meat filling vigorously in one direction for 2 minutes until it becomes sticky and emulsified.",
            "Place a dumpling wrapper on your palm, spoon 1 tablespoon of filling in the center, and moisten edges with water.",
            "Pleat and seal the edges tightly to form classic crescent dumplings.",
            "Line a bamboo steamer with parchment paper or cabbage leaves and arrange dumplings with 1/2 inch space between them.",
            "Steam over boiling water on high heat for 10-12 minutes until wrappers become translucent and juicy.",
            "Serve immediately with a dipping saucer of Chinkiang black vinegar, chili oil, and julienned ginger."
        ],
        nutrition: {
            calories: "390 kcal",
            protein: "22g",
            carbs: "38g",
            fat: "17g",
            fiber: "2g"
        }
    },
    {
        id: 25,
        name: "Traditional Rajasthani Dal Baati Churma",
        tagline: "Authentic desert delicacy of golden baked whole wheat baatis soaked in desi ghee, spicy panchmel dal & sweet churma.",
        cuisine: "Indian",
        category: "Vegetarian",
        diet: "Vegetarian",
        time: 55,
        prepTime: 20,
        cookTime: 35,
        difficulty: "Hard",
        rating: 4.9,
        reviewsCount: 360,
        calories: 680,
        servings: 4,
        spicyLevel: 3,
        featured: true,
        popular: true,
        image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Sanjeev R.",
        ingredients: [
            { name: "Coarse Whole Wheat Flour (Atta)", amount: 2, unit: "cups" },
            { name: "Semolina (Sooji / Rava)", amount: 0.5, unit: "cup" },
            { name: "Pure Desi Ghee (for dough & dipping)", amount: 0.75, unit: "cup" },
            { name: "Panchmel Dal Mix (Toor, Moong, Chana, Urad & Masoor)", amount: 1.5, unit: "cups" },
            { name: "Carom Seeds (Ajwain)", amount: 1, unit: "tsp" },
            { name: "Jaggery / Powdered Sugar (for sweet Churma)", amount: 0.5, unit: "cup" },
            { name: "Ginger, Garlic & Green Chilies (minced)", amount: 2, unit: "tbsp" },
            { name: "Hing, Cumin & Dry Red Chilies", amount: 1, unit: "tsp" },
            { name: "Turmeric & Red Chili Powder", amount: 1.5, unit: "tsp" },
            { name: "Salt", amount: 1.5, unit: "tsp" }
        ],
        instructions: [
            "For Baati: Mix wheat flour, semolina, ajwain, salt, and 4 tbsp melted ghee. Knead into a stiff, firm dough with warm water. Divide into smooth round balls.",
            "Bake baatis in a preheated tandoor, oven, or baati maker at 200°C (400°F) for 25-30 minutes, turning halfway until golden brown and crackled on top.",
            "For Panchmel Dal: Pressure cook mixed 5 lentils with turmeric, salt, and water for 4 whistles until soft. Whisk gently.",
            "Heat ghee in a pan, crackle cumin seeds, dry red chilies, hing, garlic, ginger, and chili powder. Pour hot tempering into the dal and simmer for 5 minutes.",
            "For Churma: Crush 2 hot baked baatis into fine crumbs while warm. Mix with 3 tbsp warm ghee, powdered jaggery, cardamom, and chopped almonds.",
            "To serve: Lightly crack the hot baatis and submerge completely into a bowl of warm desi ghee.",
            "Serve hot dipped baatis alongside spicy panchmel dal, sweet churma, and raw onions with lemon."
        ],
        nutrition: {
            calories: "680 kcal",
            protein: "21g",
            carbs: "84g",
            fat: "31g",
            fiber: "12g"
        }
    },
    {
        id: 26,
        name: "Traditional French Beef Bourguignon",
        tagline: "Classic Parisian braised beef chunks slow-cooked in rich Burgundy Pinot Noir with baby pearl onions & portobello mushrooms.",
        cuisine: "Mediterranean",
        category: "Non-Vegetarian",
        diet: "Non-Vegetarian",
        time: 75,
        prepTime: 20,
        cookTime: 55,
        difficulty: "Hard",
        rating: 4.9,
        reviewsCount: 275,
        calories: 640,
        servings: 4,
        spicyLevel: 1,
        featured: false,
        popular: true,
        image: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?auto=format&fit=crop&w=1000&q=80",
        author: "Chef Jean-Luc Dubois",
        ingredients: [
            { name: "Beef Chuck Roast (cut into 2-inch cubes)", amount: 700, unit: "g" },
            { name: "French Red Wine (Burgundy or Pinot Noir)", amount: 2, unit: "cups" },
            { name: "Rich Beef Bone Broth", amount: 2, unit: "cups" },
            { name: "Baby Pearl Onions (peeled)", amount: 1, unit: "cup" },
            { name: "Cremini / Portobello Mushrooms (quartered)", amount: 250, unit: "g" },
            { name: "Carrots (sliced into thick chunks)", amount: 2, unit: "items" },
            { name: "Thick Cut Smoked Bacon (lardons)", amount: 100, unit: "g" },
            { name: "Tomato Paste & Garlic", amount: 2, unit: "tbsp" },
            { name: "Fresh Thyme sprigs & Bay leaves (Bouquet Garni)", amount: 3, unit: "sprigs" },
            { name: "Butter and Flour for thickening", amount: 2, unit: "tbsp" }
        ],
        instructions: [
            "In a heavy French Dutch oven, crisp the bacon lardons over medium heat, then transfer bacon to a plate, leaving the fat in the pot.",
            "Pat beef cubes completely dry with paper towels, season with salt and pepper, and sear in batches in the hot fat until deeply browned on all sides. Remove beef.",
            "Add carrots and sliced onions to the pot and sauté for 4 minutes. Stir in tomato paste and minced garlic.",
            "Return the seared beef and bacon to the pot. Dust with 2 tbsp flour and toss to coat.",
            "Pour in the full-bodied red wine and beef broth, scraping up all the flavorful caramelized bits from the bottom of the Dutch oven.",
            "Tuck in fresh thyme and bay leaves. Cover tightly and braise on low heat for 50-60 minutes until the beef is melt-in-the-mouth fork tender.",
            "In a separate skillet, sauté quartered mushrooms and pearl onions in butter until golden, then fold into the stew for the final 10 minutes of cooking.",
            "Serve steaming hot over buttery mashed potatoes or buttered egg noodles with fresh chopped parsley."
        ],
        nutrition: {
            calories: "640 kcal",
            protein: "48g",
            carbs: "24g",
            fat: "36g",
            fiber: "4g"
        }
    }
];

// Helper to get recipe by ID
function getRecipeById(id) {
    return RECIPES_DATA.find(r => r.id === parseInt(id, 10)) || null;
}

// Helper to get random recipe
function getRandomRecipe() {
    const randomIndex = Math.floor(Math.random() * RECIPES_DATA.length);
    return RECIPES_DATA[randomIndex];
}
